
    alter table User_roles 
        drop constraint FKEA147569DCD93557

    drop table BlogEntry if exists

    drop table User if exists

    drop table User_roles if exists

    create table BlogEntry (
        id bigint generated by default as identity,
        authorName varchar(255),
        content clob,
        creationDate timestamp,
        lastUpdateDate timestamp,
        title varchar(255),
        primary key (id)
    )

    create table User (
        name varchar(255) not null,
        password varchar(255),
        primary key (name)
    )

    create table User_roles (
        User_name varchar(255) not null,
        roles varchar(255)
    )

    alter table User_roles 
        add constraint FKEA147569DCD93557 
        foreign key (User_name) 
        references User
